import { RegisteredHardware } from '../types';

export const DEFAULT_HARDWARE_LIST: RegisteredHardware[] = [
    { id: 'hw_1', name: 'MDF BRANCO 15MM', category: 'Chapa', price: 230.00 },
    { id: 'hw_2', name: 'MDF CINZA ASFALTO 15MM', category: 'Chapa', price: 350.00 },
    { id: 'hw_3', name: 'MDF ROSA MILKSHAKE', category: 'Chapa', price: 410.00 },
    { id: 'hw_4', name: 'MDF PRETO 15MM', category: 'Chapa', price: 350.00 },
    { id: 'hw_5', name: 'MDF FLORESTA 15MM', category: 'Chapa', price: 340.00 },
    { id: 'hw_6', name: 'MDF AMADEIRADO', category: 'Chapa', price: 350.00 },
    { id: 'hw_7', name: 'DURAPLAC', category: 'Chapa', price: 100.00 },
    { id: 'hw_8', name: 'RIPÃO REVESTIDO', category: 'Perfil', price: 5.00 },
    { id: 'hw_9', name: 'COMPENSADO', category: 'Chapa', price: 200.00 },
    { id: 'hw_10', name: 'METALON GALVANIZADO', category: 'Perfil', price: 6.00 },
    { id: 'hw_11', name: 'METALON 30X30', category: 'Perfil', price: 9.17 },
    { id: 'hw_12', name: 'METALON 20X20', category: 'Perfil', price: 7.00 },
    { id: 'hw_13', name: 'METALON 50X30', category: 'Perfil', price: 13.00 },
    { id: 'hw_14', name: 'MDF BRANCO 6MM', category: 'Chapa', price: 170.00 },
    { id: 'hw_15', name: 'PAINEL CANALETADO', category: 'Chapa', price: 380.00 },
    { id: 'hw_16', name: 'FITA BRANCA', category: 'Fita', price: 0.50 },
    { id: 'hw_17', name: 'FITA PRETA', category: 'Fita', price: 0.90 },
    { id: 'hw_18', name: 'FITA CINZA ASFALTO', category: 'Fita', price: 2.50 },
    { id: 'hw_19', name: 'FITAS DE COR', category: 'Fita', price: 2.75 },
    { id: 'hw_20', name: 'PARAFUSO 35x16', category: 'Parafuso', price: 0.05 },
    { id: 'hw_21', name: 'PARAFUSO 4x40', category: 'Parafuso', price: 0.10 },
    { id: 'hw_22', name: 'PARAFUSO 25X 35', category: 'Parafuso', price: 0.08 },
    { id: 'hw_23', name: 'PARAFUSO 60X60', category: 'Parafuso', price: 0.45 },
    { id: 'hw_24', name: 'CANTONEIRA', category: 'Acessório', price: 0.20 },
    { id: 'hw_25', name: 'TAPAFURO', category: 'Acessório', price: 0.06 },
    { id: 'hw_26', name: 'BUCHA N8', category: 'Acessório', price: 0.10 },
    { id: 'hw_27', name: 'BUCHA N6', category: 'Acessório', price: 0.05 },
    { id: 'hw_28', name: 'PREGOS 0,8 X 0,8', category: 'Acessório', price: 60.00 },
    { id: 'hw_29', name: 'COLA BRANCA', category: 'Cola', price: 16.00 },
    { id: 'hw_30', name: 'COLA DE CONTATO', category: 'Cola', price: 67.00 },
    { id: 'hw_31', name: 'PUXADORE REDONDO', category: 'Puxador', price: 3.00 },
    { id: 'hw_32', name: 'PUXADORE HASTE', category: 'Puxador', price: 5.00 },
    { id: 'hw_33', name: 'CORREDIÇA STEEL REFORÇADA', category: 'Corrediça', price: 17.00 },
    { id: 'hw_34', name: 'CORREDIÇA 400MM', category: 'Corrediça', price: 11.00 },
    { id: 'hw_35', name: 'CORREDIÇA 350MM', category: 'Corrediça', price: 9.50 },
    { id: 'hw_36', name: 'CORREDIÇA 300MM', category: 'Corrediça', price: 9.00 },
    { id: 'hw_37', name: 'CORREDIÇA 250MM', category: 'Corrediça', price: 8.50 },
    { id: 'hw_38', name: 'DOBRADIÇA RETA C/ PISTÃO', category: 'Dobradiça', price: 3.20 },
    { id: 'hw_39', name: 'DOBRADIÇA CURVA C/ PISTÃO', category: 'Dobradiça', price: 3.20 },
    { id: 'hw_40', name: 'DOBRADIÇA SUPERCURVA C/ PISTÃO', category: 'Dobradiça', price: 3.20 },
    { id: 'hw_41', name: 'DOBRADIÇA CAMARÃO C/ PISTÃO', category: 'Dobradiça', price: 31.00 },
    { id: 'hw_42', name: 'Dobradiça Flo Aco 3/12 C/3', category: 'Dobradiça', price: 22.90 },
    { id: 'hw_43', name: 'PREGOS', category: 'Acessório', price: 0.01 },
    { id: 'hw_44', name: 'VERNIZ', category: 'Acabamento', price: 25.00 },
    { id: 'hw_45', name: 'Pé Palito', category: 'Acessório', price: 8.00 },
    { id: 'hw_46', name: 'Tubo Cabideiro', category: 'Acessório', price: 10.65 },
    { id: 'hw_47', name: 'suporte cabideiro', category: 'Acessório', price: 1.00 },
    { id: 'hw_48', name: 'CANTONEIRA EM L', category: 'Acessório', price: 1.50 },
    { id: 'hw_49', name: 'SUPORTE INVISÍVEL', category: 'Acessório', price: 7.00 },
    { id: 'hw_50', name: 'PÉS BRANCO P/ ORGANIZADOR', category: 'Acessório', price: 4.00 },
    { id: 'hw_51', name: 'PERFIL PUXADOR ALUMÍNIO', category: 'Puxador', price: 21.67 },
    { id: 'hw_52', name: 'PERFIL PUXADOR INOX', category: 'Puxador', price: 28.00 },
    { id: 'hw_53', name: 'PERFIL PUXADOR BRONZE', category: 'Puxador', price: 35.00 },
    { id: 'hw_54', name: 'SISTEMA PORTA DE CORRER MAIOR', category: 'Sistema', price: 56.00 },
    { id: 'hw_55', name: 'SISTEMA PORTA DE CORRER MENOR', category: 'Sistema', price: 25.00 },
    { id: 'hw_56', name: 'TRILHO P/ PORTA INFERIOR', category: 'Trilho', price: 24.00 },
    { id: 'hw_57', name: 'TRILHO P/ PORTA SUPERIOR', category: 'Trilho', price: 26.00 },
    { id: 'hw_58', name: 'SUPORTE PAINEL', category: 'Acessório', price: 10.00 },
    { id: 'hw_59', name: 'PERFIL DE BORDA', category: 'Perfil', price: 5.50 },
    { id: 'hw_60', name: 'SAPATAS PEQUENAS', category: 'Acessório', price: 0.40 },
    { id: 'hw_61', name: 'SAPATAS NIVELADORAS', category: 'Acessório', price: 4.00 },
    { id: 'hw_62', name: 'GANCHOS PEQUENOS', category: 'Acessório', price: 1.30 },
    { id: 'hw_63', name: 'BOCAL DE LÂMPADAS', category: 'Elétrica', price: 2.00 },
    { id: 'hw_64', name: 'RODÍZIO COM FREIO', category: 'Acessório', price: 7.50 },
    { id: 'hw_65', name: 'RODÍZIO SEM FREIO', category: 'Acessório', price: 6.50 },
    { id: 'hw_66', name: 'ESPELHO', category: 'Vidro', price: 92.11 },
    { id: 'hw_67', name: 'VIDRO 4mm', category: 'Vidro', price: 190.00 },
    { id: 'hw_68', name: 'VIDRO 6mm', category: 'Vidro', price: 328.00 },
    { id: 'hw_69', name: 'PÉS DE METAL QUADRADO', category: 'Acessório', price: 9.90 },
    { id: 'hw_70', name: 'SUPORTE P/ VIDRO 6MM', category: 'Acessório', price: 1.00 },
    { id: 'hw_71', name: 'COPINHO DE LD', category: 'Acessório', price: 10.00 },
    { id: 'hw_72', name: 'PULSADOR', category: 'Acessório', price: 3.00 },
    { id: 'hw_73', name: 'BASCULANTE', category: 'Acessório', price: 8.00 },
    { id: 'hw_74', name: 'PERFIL DE ACABAMENTO', category: 'Perfil', price: 10.50 },
    { id: 'hw_75', name: 'LÂMPADAS PARA CAMARIM', category: 'Elétrica', price: 2.70 },
    { id: 'hw_76', name: 'ARTICULADOR PARA SAPATEIRA', category: 'Acessório', price: 25.00 },
    { id: 'hw_77', name: 'PERFIL - PORTA DE ESPELHO', category: 'Perfil', price: 33.33 },
    { id: 'hw_78', name: 'ISOPOR 25MM', category: 'Outros', price: 20.00 },
    { id: 'hw_79', name: 'SISTEMA PORTA - INTERIOR', category: 'Sistema', price: 70.00 },
    { id: 'hw_80', name: 'TRILHO P/ PORTA - INTERIOR', category: 'Trilho', price: 50.00 },
    { id: 'hw_81', name: 'PERFIL PUX PORTA DE ESPELHO', category: 'Perfil', price: 36.67 }
];
